version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports: [ "1883:1883" ]
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on: [mqtt]
    ports: [ "8000:8000" ]

  sensor_reader:
    build: ./sensor_reader
    container_name: sensor_reader
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - MODE=mock         # set to 'real' to use real OBD/CAN drivers
    depends_on: [mqtt]

  fusion_service:
    build: ./fusion_service
    container_name: fusion_service
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    depends_on: [mqtt]
